# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "timind-reviews-app"
client_id = "262c7ddbcacda829e1ccfd75bf98cc94"
application_url = "https://campus-appendix-boot-tower.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://campus-appendix-boot-tower.trycloudflare.com/auth/callback",
  "https://campus-appendix-boot-tower.trycloudflare.com/auth/shopify/callback",
  "https://campus-appendix-boot-tower.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quick-start-6058d68b.myshopify.com"
